void bus_do_U32(SIM_TYPE__U32 * bus[]);
void bus_do_U16(SIM_TYPE__U16 * bus[]);
void bus_do_U08(SIM_TYPE__U08 * bus[]);
void bus_do_I32(SIM_TYPE__I32 * bus[]);
void bus_do_I16(SIM_TYPE__I16 * bus[]);
void bus_do_I08(SIM_TYPE__I08 * bus[]);
void bus_do_F32(SIM_TYPE__F32 * bus[]);
void bus_do_F64(SIM_TYPE__F64 * bus[]);
void bus_do_W01(SIM_TYPE__W01 * bus[]);
