bus.o: bus.c common.h config.h bus.h
code.o: code.c util.h common.h config.h code.h
common.o: common.c common.h util.h line.h config.h
config.o: config.c config.h common.h util.h
global.o: global.c util.h common.h config.h global.h
graph.o: graph.c common.h graph.h util.h config.h
line.o: line.c common.h line.h
main.o: main.c stage.h common.h
module.o: module.c common.h util.h config.h module.h
parse.o: parse.c util.h common.h config.h parse.h
pre.o: pre.c common.h util.h config.h line.h pre.h
stage.o: stage.c stage.h common.h util.h parse.h module.h global.h code.h \
  config.h pre.h bus.h
tags.o: tags.c tags.h
util.o: util.c util.h
verilog.o: verilog.c common.h util.h verilog.h code.h
